// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_Stud_Proj;

#nullable disable

namespace My_Stud_Proj.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("My_Stud_Proj.Models.DeveloperDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("About")
                        .HasColumnType("longtext");

                    b.Property<string>("CertificatesString")
                        .HasColumnType("longtext");

                    b.Property<string>("DbString")
                        .HasColumnType("longtext");

                    b.Property<string>("IdeString")
                        .HasColumnType("longtext");

                    b.Property<string>("LibrariesString")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtherSkillsString")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProgramLangString")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("РhotoPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("My_Stud_Proj.Models.FeedbackDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("FeedbackGrade")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("FeedbackUpdate")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("FeedbacksDbListId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserAvatarPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("UserGameWinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserTotalGameAttempts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbacksDbListId");

                    b.ToTable("FeedbackDb");
                });

            modelBuilder.Entity("My_Stud_Proj.Models.FeedbacksDbList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TotalGrade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FeedbacksList");
                });

            modelBuilder.Entity("My_Stud_Proj.Models.UserDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("GameWinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GamesListString")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Geolocation")
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SortingDevListValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SortingFdbackListValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalGameAttempts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("My_Stud_Proj.Models.FeedbackDb", b =>
                {
                    b.HasOne("My_Stud_Proj.Models.FeedbacksDbList", "FeedbacksDbList")
                        .WithMany("List")
                        .HasForeignKey("FeedbacksDbListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedbacksDbList");
                });

            modelBuilder.Entity("My_Stud_Proj.Models.FeedbacksDbList", b =>
                {
                    b.Navigation("List");
                });
#pragma warning restore 612, 618
        }
    }
}
